#!/bin/bash
while [ "$select" != "Lock" -a "$select" != "Logout" -a "$select" != "Shutdown"  ]; do
    select=$(echo -e 'Lock\nLogout\nShutdown' | dmenu -nb '#2f343f' -nf '#f3f4f5' -sb '#9575cd' -sf '#f3f4f5' -fn '-*-*-medium-r-normal-*-*-*-*-*-*-100-*-*' -i -p "Select option:")
    [ -z "$select" ] && exit 0
done
[ "$select" = "Lock" ] && i3lock -c "#000000" -i ~/.i3/wallpapers/lockscreen.png
[ "$select" = "Logout" ] && i3-msg exit
[ "$select" = "Shutdown" ] && systemctl poweroff