#!/bin/bash

SESSION_NAME="dev"
START_FOLDER=""


path="$(tr [A-Z] [a-z] <<< "$1")"

if [ "$path" == 'shop' ]; then
   START_FOLDER='~/projects/zugseil7.shop.ui' 
fi

tmux has-session -t $SESSION_NAME 2>/dev/null

if [ $? != 0 ]; then
tmux new-session  -s $SESSION_NAME -d -x "$(tput cols)" -y "$(tput lines)"

tmux split-window -h -p 30

tmux select-pane -t 1
tmux split-window -v -p 40

tmux select-pane -t 1
tmux send-keys -t $SESSION_NAME "cd $START_FOLDER && clear" C-m

tmux select-pane -t 2
tmux send-keys -t $SESSION_NAME "cd $START_FOLDER && clear" C-m

tmux select-pane -t 0
tmux send-keys -t $SESSION_NAME "cd $START_FOLDER && clear" C-m
fi

tmux attach -t $SESSION_NAME 
